### ISSUE TITLE
[SQLite3] Foreign key constraint not working

### ISSUE THREAD

**Issue by msrumon** [msrumon/warehouse-manager#1]
I have a foreign key constraint which prevents the parent record from removing if any child records exist:
https://github.com/msrumon/warehouse-manager/blob/7a16d7f9a4fbf78b6dfac57c1735f1e8fe9e70e8/helpers/Database.php#L32
But this doesn't work. I am able to delete parent record (and in turn deleting child records as well), but I want to prevent that. How can I do it?

**Comment by waiyant** [comment]
Hello msrumon!

Try to add the following statement before Line 56 of Database.php (inside the function getConnection(), before returning the connection object).
`$this->connection->exec('PRAGMA foreign_keys = ON');`

This statement could ensure a foreign key enforcement.
You can read more here:
https://www.sqlite.org/pragma.html#pragma_foreign_keys

Good day!

**Comment by msrumon** [comment]
Hi, thanks for taking your time to have a look at the issue. I tried that already, before even pushing the first commit, but it didn't work. What doesn't work exactly? After running `PRAGMA foreign_keys` against the database directly, it returns `0`. As long as I run the command against the database directly, it turns on. But after turning it on from CLI, it also doesn't work (constraint doesn't kick in). When I check the status again, I get `0`. Looks like it turns off between somewhere. This is what I'm currently investigating. But I don't want to spend too much time though, I have plan to implement DBAL library, and this problem won't be there I hope. Anyway, thanks again.

**Comment by waiyant** [comment]
Hello!
I copied your project to my Apache server (PHP 7.3.4), and the FK constraints work properly after adding `PRAGMA foreign_keys = ON`.

PHP gave the following error message, seems the FK integrity check did kick in.
`Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 constraint failed in /*/warehouse-manager-master/supplier-delete.php:65 Stack trace: #0 /*/warehouse-manager-master/supplier-delete.php(65): PDOStatement->execute() #1 {main} thrown in /*/warehouse-manager-master/supplier-delete.php on line 65`

Did you apply the PRAGMA statement on every connection?

**Comment by msrumon** [comment]
Hi, can you please send a PR from a new branch? I would love to see it by myself. ☺️  Thanks in advance.

**Comment by waiyant** [comment]
Thank you for merging my PR!
So finally does it work in your side?
This was my first ever pull request, so just want to say thank you! :)

**Comment by msrumon** [comment]
Yes it worked from my side! And you're most welcomed, I really appreciate your contribution. I wish you all the best for your future.
